#!/bin/bash

#####
#环境变量以如下形式设置
#然后可以在request文件中使用
#列出所有环境：POSTor config listenv
#列出所有环境变量：POSTor config listenv -m
#查看默认环境的变量：POSTor config defaultenv %查看命令%
#添加新的环境:POSTor config addenv %环境名%
#####

#export key1=value1
#export key2=value2
