#!/bin/bash
silent=""

currdir=$(pwd)
scriptdir=$(
    cd $(dirname $0)
    pwd
)
home=$(
    cd ~
    pwd
)
$(cd $currdir)
mydir="$home/.postor"
#
envdir="$mydir/enviroments"
hisdir="$mydir/histories"
hisfile="$hisdir/history"
lastfile="$hisdir/last"
configfile="$mydir/config.POSTor"
reqdir="$mydir/requests"
templdir="$scriptdir/template"
envtempl="$templdir/envtempl"
reqtempl="$templdir/requesttempl"
defaultenv="$envdir/default"

function help() {
    echo -e 'usage:
    POSTor config -e default-environment'
}

function executeall() {
    local valid=("vim" "less" "tail" "more" "cat")
    for cmd in ${valid[*]}; do
        if [ "$1" = "$cmd" ]; then
            local var1="1"
            local var2=$1
            shift
            echo $* | xargs >&2 -o $var2
        fi
    done
    if [ -z "$var1" ]; then
        echo "unsupported command $1"
        exit 1
    fi
}

function configuration() {
    case $1 in
    env)
        shift
        case $1 in
        -a | --add)
            if [ -z "$2" ]; then
                echo "请指定环境名"
                exit 1
            fi
            tfname=$envdir/"$2"
            touch "$tfname"
            cp "$envtempl" "$tfname"
            executeall vim "$tfname"
            ;;
        -d | --default)
            if [ -n "$2" ] && [ "$2"="-e" ]; then
                executeall vim "$defaultenv"
            else
                executeall less "$defaultenv"
            fi
            ;;
        -l | --list)
            if [ -n "$2" ] && [ $2 = "-m" ]; then
                local more="1"
            fi
            var2=""
            for var1 in "$envdir"/*; do
                var2="$var2$var1\n"
                if [ -n "$more" ]; then
                    while read var0; do
                        if [ ! "${var0:0:1}" = "#" ]; then
                            var2="$var2\t${var0:7}\n"
                        fi
                    done <$var1
                fi
            done
            echo -e $var2
            ;;
        -D | --delete)
            if [ -z "$2" ]; then
                help
            else
                echo ""
            fi
            ;;
        *) help ;;
        esac
        ;;
    esac
}
function puthis() {
    cd "$hisdir"
    local fs=$(find . -name "*-his" | sort -t '-' -nrk 1.3)
    if [ -n "$fs" ]; then
        local fsl=$((10#${fs:2:6}))
        ((fsl++))
    else
        local fsl=000001
    fi
    cd $currdir
    local his1="\n##$(printf "%06d" $fsl)######"$(date)"############\n"
    local his2="#!/bin/bash"
    if [ -n "$method" ]; then
        his1="$his1\nmethod: $method"
        his2="$his2\nmethod=\"$method\""
    fi
    if [ -n "$url" ]; then
        his1="$his1\nurl: $url"
        his2="$his2\nurl=\"$url\""
    fi
    if [ -n "$header" ]; then
        his1="$his1\nheader:$header"
        his2="$his2\nheader=\"$header\""
    fi
    if [ -n "$request" ]; then
        his1="$his1\nrequest:\n$request"
        his2="$his2\nrequest='$request'"
    fi
    if [ -n "$response"]; then
        his1="$his1\nresponse:\n$1"
    fi
    echo -e "$his1" >>"$hisfile"
    echo -e "$his2" >"$hisdir/$(printf "%06d" $fsl)-his"
}

function putlast() {
    echo "$1" | tee "$lastfile"
}

function curlbox() {
    local cmd=()
    local i=0
    if [ -n "$silent" ]; then
        cmd[i]="-s"
        ((i++))
    fi
    if [ -n "$header" ]; then
        cmd[i]="-H"
        ((i++))
        cmd[i]="$header"
        ((i++))
    fi
    if [ -n "$method" ]; then
        cmd[i]="-X"
        ((i++))
        cmd[i]="$method"
        ((i++))
    fi
    if [ -n "$request" ]; then
        cmd[i]="-d"
        ((i++))
        cmd[i]="$request"
        ((i++))
    fi
    if [ -n "$url" ]; then
        cmd[i]="$url"
    else
        echo "no url"
        exit 1
    fi
    local tres=$(curl 2>/dev/null "${cmd[@]}")
    putlast $tres
    puthis $tres
}

function sourcepara() {
    source "$reqdir/$1"
}

function dealbasic() {
    sourcepara $1
    curlbox
}

function fileselector() {
    export -f "$1"
    export -f sourcepara
    export -f curlbox
    export reqdir
    local var1=0
    for var2 in $(find "$2" -name $(echo $3 | sed -e 's/./*&/g' -e 's/$/&*/g')); do
        local files[$var1]=${var2:${#2}+1}
        ((var1++))
    done
    if [ ${#files[@]} -eq 0 ]; then
        echo "没有找到匹配请求"
        exit 0
    elif [ ${#files[@]} -eq 1 ]; then
        echo "${files[0]}" | xargs -I {} bash -c "$1 \"{}\""
    elif [ ${#files[@]} -ge 2 ]; then
        PS3="选择一个请求处理："
        select option in ${files[*]}; do
            if [ $REPLY -gt 0 ] 2>/dev/null; then
                if [ $REPLY -le ${#files[@]} ]; then
                    echo "${files[$REPLY - 1]}" | xargs -I {} bash -c "$1 \"{}\""
                    break
                fi
            fi
            echo "输入编号"
        done
    fi
}

function single() {
    while [ -n "$1" ]; do
        case $1 in
        -s | --silent)
            silent="1"
            shift
            ;;
        *)
            fileselector dealbasic $reqdir $@ &
            shift $#
            ;;
        esac
    done
}

function last() {
    if [ -n "$1" ]; then
        executeall $* ${lastfile}
    else
        executeall cat ${lastfile}
    fi
}

function histories() {
    if [ "$1" -gt 0 ] 2>/dev/null; then
        if [ -e "$hisdir/$(printf "%06d" $1)-his" ]; then
            sourcepara "../histories/$(printf "%06d" $1)-his"
            curlbox
        else
            echo "历史$(printf "%06d" $1)-his不存在"
        fi
    elif [ -n "$1" ]; then
        executeall $* ${hisfile}
    else
        executeall less ${hisfile}
    fi
}

#main ##################

if [ -f "$configfile" ]; then
    source "$configfile"
    if [ -n "$requestdir" ]; then
        reqdir="$requestdir"
    fi
fi

if [ -f "$defaultenv" ]; then
    source "$defaultenv"
fi

if [ ! -d "$hisdir" ]; then
    mkdir -p "$hisdir"
fi

if [ ! -d "$reqdir" ]; then
    mkdir -p "$reqdir"
    cp "$reqtempl" "$reqdir/templ"
fi

if [ ! -d "$envdir" ]; then
    mkdir -p "$envdir"
    cp "$envtempl" "$defaultenv"
fi


if [ ! -n "$1" ]; then
    help
else
    while [ -n "$1" ]; do
        case $1 in
        -h | --help) help ;;
        config)
            shift
            configuration $@
            shift $#
            ;;
        single)
            shift
            single $@
            shift $#
            ;;
        last)
            shift
            last $@
            shift $#
            ;;
        his)
            shift
            histories $@
            shift $#
            ;;
        *)
            help
            ;;
        esac
        shift
    done
fi
#main end##############
